const { contextBridge, ipcRenderer } = require('electron');

// 所有 on* 订阅统一经此注册，并回传退订函数：渲染层若重新初始化，
// 不退订就会叠加监听器，同一条通知被回调多次。
function subscribe(channel, handler) {
  ipcRenderer.on(channel, handler);
  return () => ipcRenderer.removeListener(channel, handler);
}

contextBridge.exposeInMainWorld('notchAPI', {
  quitApp: () => ipcRenderer.invoke('app:quit'),
  setMode: (mode) => ipcRenderer.invoke('window:set-mode', mode),
  beginCollapse: () => ipcRenderer.invoke('window:begin-collapse'),
  setTab: (tab) => ipcRenderer.invoke('window:set-tab', tab),
  showQuickIsland: (options) => ipcRenderer.invoke('quick-island:show', options),
  hideQuickIsland: (options) => ipcRenderer.invoke('quick-island:hide', options),
  openIslandWorkspace: (tab, motion) => ipcRenderer.invoke('quick-island:open-workspace', tab, motion),
  returnToQuickIsland: (motion) => ipcRenderer.invoke('quick-island:return', motion),
  surfaceReady: (handoffId, motionReady) => ipcRenderer.send('window:surface-ready', handoffId, motionReady),
  completeWindowMotion: (handoffId) => ipcRenderer.invoke('window:motion-complete', handoffId),
  onWindowMotionPlay: (cb) => subscribe('window:motion-play', (_event, id) => cb(id)),
  onWindowMotionCleanup: (cb) => subscribe('window:motion-cleanup', (_event, id) => cb(id)),
  onQuickIslandShow: (cb) => subscribe('quick-island:show', (event, metrics) => cb(metrics)),
  onQuickIslandHide: (cb) => subscribe('quick-island:hide', (event, payload) => cb(payload)),
  onOpenIslandWorkspace: (cb) => subscribe('island:open-workspace', (event, tab, options) => cb(tab, options)),
  getSystemVolume: () => ipcRenderer.invoke('system:volume:get'),
  setSystemVolume: (volume) => ipcRenderer.invoke('system:volume:set', volume),
  getSystemStatus: () => ipcRenderer.invoke('system:status:get'),
  onSystemStatus: (cb) => subscribe('island:system-status', (event, payload) => cb(payload)),
  getComputerStatus: () => ipcRenderer.invoke('computer:status'),
  onComputerStatus: (cb) => subscribe('computer:status-changed', (event, payload) => cb(payload)),
  getQuickLaunchApps: () => ipcRenderer.invoke('quick-launch:list'),
  chooseQuickLaunchApp: (id) => ipcRenderer.invoke('quick-launch:choose', id),
  launchQuickApp: (id) => ipcRenderer.invoke('quick-launch:open', id),
  openWeatherApp: () => ipcRenderer.invoke('quick-launch:weather'),
  getWeather: (city) => ipcRenderer.invoke('weather:get', city),
  controlPomodoro: (payload) => ipcRenderer.invoke('pomodoro:control', payload),
  onPomodoroControl: (cb) => subscribe('pomodoro:control', (event, payload) => cb(payload)),
  acknowledgePomodoroControl: (requestId) => ipcRenderer.send('pomodoro:controlled', requestId),
  onStatusIslandShow: (cb) => subscribe('island:status-show', (event, payload) => cb(payload)),
  updateStatusIslandSurface: (payload) => ipcRenderer.send('island:status-surface', payload),
  onStatusIslandMaterial: (cb) => subscribe('island:status-material', (_event, payload) => cb(payload)),
  onStatusIslandHide: (cb) => subscribe('island:status-hide', () => cb()),
  holdStatusIsland: (held) => ipcRenderer.send('island:status-hold', held),
  dismissStatusIsland: () => ipcRenderer.invoke('island:status-dismiss'),
  updateIslandActivity: (state) => ipcRenderer.send('island:activity-update', state),
  getIslandActivities: () => ipcRenderer.invoke('island:activities-get'),
  onIslandActivities: (cb) => subscribe('island:activities', (event, payload) => cb(payload)),
  ensureCamera: () => ipcRenderer.invoke('media:camera'),
  ensureMicrophone: () => ipcRenderer.invoke('media:microphone'),
  openExternal: (url) => ipcRenderer.invoke('shell:openExternal', url),
  openPath: (p) => ipcRenderer.invoke('shell:openPath', p),
  openPrivacySettings: (pane) => ipcRenderer.invoke('shell:open-privacy-settings', pane),
  getAICodeStatus: () => ipcRenderer.invoke('ai-code:get'),
  refreshAICode: (id) => ipcRenderer.invoke('ai-code:refresh', id),
  connectAICode: (id) => ipcRenderer.invoke('ai-code:connect', id),
  onAICodeStatus: (cb) => subscribe('ai-code:status', (event, payload) => cb(payload)),
  getAITools: () => ipcRenderer.invoke('ai-tools:get'),
  updateAITools: (request) => ipcRenderer.invoke('ai-tools:update', request),
  openAIToolWebsite: (id) => ipcRenderer.invoke('ai-tools:website', id),
  onAIToolsChanged: (cb) => subscribe('ai-tools:changed', (event, payload) => cb(payload)),
  getCodexFloatStatus: () => ipcRenderer.invoke('codex-float:get'),
  refreshCodexFloat: () => ipcRenderer.invoke('codex-float:refresh'),
  openCodexThread: (id) => ipcRenderer.invoke('codex-float:open-thread', id),
  openCodexApp: () => ipcRenderer.invoke('codex-float:open-app'),
  onCodexFloatStatus: (cb) => subscribe('codex-float:status', (event, payload) => cb(payload)),
  inspectLink: (url) => ipcRenderer.invoke('links:inspect', url),
  listWindows: () => ipcRenderer.invoke('windows:list'),
  focusWindow: (windowId) => ipcRenderer.invoke('windows:focus', windowId),
  saveRecording: (payload) => ipcRenderer.invoke('recordings:save', payload),
  readRecording: (audioPath) => ipcRenderer.invoke('recordings:read', audioPath),
  deleteRecording: (audioPath) => ipcRenderer.invoke('recordings:delete', audioPath),
  revealRecording: (audioPath) => ipcRenderer.invoke('recordings:reveal', audioPath),
  organizeMaterial: (payload) => ipcRenderer.invoke('smart:organize-material', payload),
  listCredentials: () => ipcRenderer.invoke('credentials:list'),
  getCredential: (id) => ipcRenderer.invoke('credentials:get', id),
  saveCredential: (payload) => ipcRenderer.invoke('credentials:save', payload),
  deleteCredentials: (ids) => ipcRenderer.invoke('credentials:delete-many', ids),
  copyCredential: (id, field) => ipcRenderer.invoke('credentials:copy', { id, field }),
  getTranscriptionConfig: () => ipcRenderer.invoke('transcription:get-config'),
  setTranscriptionConfig: (config) => ipcRenderer.invoke('transcription:set-config', config),
  startTranscription: () => ipcRenderer.invoke('transcription:start'),
  sendTranscriptionAudio: (bytes) => ipcRenderer.send('transcription:audio', bytes),
  finishTranscription: () => ipcRenderer.invoke('transcription:finish'),
  onTranscriptionEvent: (cb) => subscribe('transcription:event', (event, payload) => cb(payload)),
  listTaskCompletions: () => ipcRenderer.invoke('tasks:recent'),
  scheduleTodoReminders: (items) => ipcRenderer.invoke('todos:schedule-reminders', items),
  notifyPomodoro: (minutes) => ipcRenderer.invoke('pomodoro:notify', minutes),
  onTodoReminder: (cb) => subscribe('todo:reminded', (event, payload) => cb(payload)),
  onEscape: (cb) => subscribe('key:escape', () => cb()),
  onToggleShortcut: (cb) => subscribe('shortcut:toggle-panel', () => cb()),
  getHoverSpaceStatus: () => ipcRenderer.invoke('shortcut:hover-space-status'),
  getAppSettings: () => ipcRenderer.invoke('settings:get'),
  getWindowSizeSettings: () => ipcRenderer.invoke('window-size:get'),
  setWindowSizePreset: (presetId) => ipcRenderer.invoke('window-size:set', presetId),
  onWindowSizeSettingsChanged: (cb) => subscribe('window-size:changed', (event, snapshot) => cb(snapshot)),
  getAppearanceSettings: () => ipcRenderer.invoke('appearance:get'),
  updateAppearanceSurface: (shape) => ipcRenderer.send('appearance:surface', shape),
  setAppearancePreset: (presetId) => ipcRenderer.invoke('appearance:set', presetId),
  onAppearanceSettingsChanged: (cb) => subscribe('appearance:changed', (event, snapshot) => cb(snapshot)),
  setFeature: (featureId, enabled) => ipcRenderer.invoke('settings:set-feature', { featureId, enabled }),
  setAutoLaunch: (enabled) => ipcRenderer.invoke('settings:set-auto-launch', enabled === true),
  setPanelShortcut: (accelerator) => ipcRenderer.invoke('settings:set-shortcut', accelerator),
  onAppSettingsChanged: (cb) => subscribe('settings:changed', (event, settings) => cb(settings)),
  onRecordShortcut: (cb) => subscribe('app:record-shortcut', () => cb()),
  getWorkspace: () => ipcRenderer.invoke('workspace:get'),
  listProjectDrawer: () => ipcRenderer.invoke('projects:list'),
  mutateProjectDrawer: (action) => ipcRenderer.invoke('projects:mutate', action),
  chooseDrawerRoot: () => ipcRenderer.invoke('projects:choose'),
  openDrawerEntry: (id) => ipcRenderer.invoke('projects:open', id),
  revealDrawerEntry: (id) => ipcRenderer.invoke('projects:reveal', id),
  openDrawerRoot: () => ipcRenderer.invoke('projects:root'),
  onProjectDrawerChanged: (cb) => subscribe('projects:changed', (event, snapshot) => cb(snapshot)),
  loadWorkspaceData: () => ipcRenderer.invoke('workspace:load-data'),
  saveWorkspaceData: (storage) => ipcRenderer.invoke('workspace:save-data', storage),
  openWorkspace: () => ipcRenderer.invoke('workspace:open'),
  chooseWorkspace: () => ipcRenderer.invoke('workspace:choose'),
  onWorkspaceChanged: (cb) => subscribe('workspace:changed', (event, info) => cb(info)),
  onCollapseRequest: (cb) => subscribe('window:request-collapse', (_event, options) => cb({ immediate: options?.immediate === true })),
  getMetrics: () => ipcRenderer.invoke('window:metrics'),
  onMetricsChanged: (cb) =>
    subscribe('window:metrics-changed', (event, metrics) => cb(metrics)),
  writeClipboard: (entry) => ipcRenderer.invoke('clipboard:write', entry),
  pasteClipboard: (entry) => ipcRenderer.invoke('clipboard:paste', entry),
  readClipImage: (imagePath) => ipcRenderer.invoke('clipboard:readImage', imagePath),
  deleteClipImages: (paths) => ipcRenderer.invoke('clipboard:deleteImages', paths),
  onNewClipEntry: (cb) => subscribe('clipboard:new-entry', (evt, entry) => cb(entry)),
  onOpenClip: (cb) => subscribe('app:open-clip', () => cb()),
  onOpenApiSettings: (cb) => subscribe('app:open-api-settings', () => cb()),
  getMirrorImage: () => ipcRenderer.invoke('mirror:get-image'),
  chooseMirrorImage: () => ipcRenderer.invoke('mirror:choose-image'),
  onMirrorImageChanged: (cb) => subscribe('mirror:image-changed', (event, dataUrl) => cb(dataUrl)),
  onTaskNotification: (cb) =>
    subscribe('task-notification:show', (event, notification) => cb(notification)),
  onTaskNotificationQueue: (cb) =>
    subscribe('task-notification:queue', (event, count) => cb(count)),
  onTaskNotificationHide: (cb) =>
    subscribe('task-notification:hide', (event, eventId) => cb(eventId)),
  onTaskCompletion: (cb) =>
    subscribe('task-completion:new', (event, notification) => cb(notification)),
  taskNotificationDismissed: (eventId) =>
    ipcRenderer.send('task-notification:dismissed', eventId),
  activateTaskNotification: (eventId) =>
    ipcRenderer.invoke('task-notification:activate', eventId),
  taskNotificationHover: (paused) =>
    ipcRenderer.send('task-notification:hover', paused === true),
  updateTaskNotificationSurface: (payload) => ipcRenderer.send('task-notification:surface', payload),
  onTaskNotificationMaterial: (cb) => subscribe('task-notification:material', (_event, value) => cb(value)),
});
